document.write('<nav id="nav">');
document.write('<ul>');
document.write('<li><a href="index.html">Accueil</a></li>');
document.write('<li><a href="index.html#contact">Contact</a></li>');
document.write('<li>');
document.write('<li>');
document.write('<a>Expérience</a>');
document.write('<ul>');
document.write('<li><a href="datastorm.html">DataStorm</a></li>');
document.write('<li><a href="cozy.html">Cozy Cloud</a></li>');
document.write('<li>');
document.write('<a href="ejc.html">ENSAI junior Consultant</a>');
document.write('<ul>');
document.write('<li><a href="ejc.html#vp">Vice-Président Externe</a></li>');
document.write('<li><a href="ejc.html#cdp">Chef de Projets</a></li>');
document.write('<li><a href="ejc.html#dsi">DSI & Dev Android</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li><a href="insee.html">INSEE</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li>');
document.write('<li>');
document.write('<a>Scolarité</a>');
document.write('<ul>');
document.write('<li><a href="ensai.html">ENSAI</a></li>');
document.write('<li><a href="cpge.html">Prépa MP</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li><a href="index.html#article">Articles</a></li>');
document.write('</ul>');
document.write('</nav>');
