document.write('<div class="container">');
document.write('<div class="4u" id="contact">');
document.write('<section>');
document.write('<header class="major">');
document.write('<h2>Me contacter</h2>');
document.write('</header>');
document.write('<ul class="contact">');
document.write('<li>');
document.write('<span class="mail">Mail</span>');
document.write('<span><a href="mailto:pro@mmasson.fr">pro@mmasson.fr</a> (Chiffrement ProtonMail)</span>');
document.write('</li>');
document.write('<li>');
document.write('<span class="address">GitHub</span>');
document.write('<span><a href="http://www.github.com/tintinmar1995">tintinmar1995</a></span>');
document.write('</li>');
document.write('<li>');
document.write('<span class="address">LinkedIn</span>');
document.write('<span><a href="https://www.linkedin.com/in/martin-masson-data-scientist/">martin-masson-data-scientist</a></span>');
document.write('</li>');
document.write('</ul>');
document.write('</section>');
document.write('</div>');
document.write('</div>');
